config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  post '/attend', to: 'pages#attend'
  get '/success', to: 'pages#success'
  get '/bxkvfepycx', to: 'pages#registrations'

  get '/:country_id', to: 'countries#show', as: :country
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  # Friendly URLs
  extend FriendlyId
  friendly_id :name, use: :slugged
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  # CarrierWave Related
  mount_uploader :cover, CoverUploader

  has_many :participants
end

app/models/data_point.rb
class DataPoint < ApplicationRecord
end

app/models/fair_confirmation.rb
class FairConfirmation < ApplicationRecord
  validates :first_name, :last_name, :email, :phone, presence: true
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |record|
        csv << record.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :country

  # CarrierWave Related
  mount_uploader :logo, LogoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def show
    @country = Country.friendly.find(params[:country_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout "alternative", only: [:success]

  def index
    @countries = Country.order(name: :asc)
  end

  def attend
    registration_exists = 'Siz artıq qeydiyyatdan keçmisiniz!'
    registration_successful = 'Uqurla alindi'
    registration_unsuccessful = 'Zəhmət olmasa bir daha cəhd edin!'

    @fair_confirmation = FairConfirmation.new(fair_confirmation_params)

    if FairConfirmation.exists? email: @fair_confirmation[:email]
      redirect_to root_path, notice: registration_exists
      return
    end

    respond_to do |format|
      if @fair_confirmation.save
        format.html { redirect_to success_path }
        format.json { render :show, status: :created, location: @fair_confirmation }
      else
        format.html { redirect_to root_path, notice: registration_unsuccessful }
        format.json { render json: @fair_confirmation.errors, status: :unprocessable_entity }
      end
    end

  end

  def success
  end

  def registrations
    respond_to do |format|
      format.html
      format.csv { send_data FairConfirmation.all.to_csv }
    end
  end

  private
  
  def fair_confirmation_params
    params.require(:fair_confirmation).permit(:first_name, :last_name, :email, :phone, :source)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Meta tags
  def title(str)
    content_for(:title, content = str.to_s)
  end

  def description(str)
    content_for(:description, content = str.to_s)
  end

  def og_image(str)
    content_for(:og_image, content = str.to_s)
  end

  def classes(str)
    content_for(:classes, content = str.to_s)
  end

  def header(str)
    content_for(:header, content = str.to_s)
  end

  def summary(str)
    content_for(:summary, content = str.to_s)
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/countries/show.html.slim
- title @country.name
- description "Sizləri 12 Aprel 2018-ci il saat 12:00-dan 18:00-a kimi keçiriləcək Xaricdə təhsil sərgisinə dəvət edirik."
- og_image image_url(@country.cover)

.uk-section-default.uk-light.uk-position-relative
  div(style="background-image: url(#{image_url(@country.cover)})" class="uk-background-norepeat uk-background-cover uk-background-center-center uk-section uk-flex uk-flex-middle" uk-height-viewport="offset-top: true")
    .uk-position-cover(style="background-color: rgba(0, 0, 0, 0.4)")
    .uk-width-1-1
      .uk-container
        .uk-margin-remove-adjacent
        .uk-margin-medium
          div
            h2.uk-text-center.h6.uk-scrollspy-inview.uk-animation-fade(class="uk-hidden@s")
              span 12 Aprel 2018-ci il saat 12:00
            h1.uk-text-center.uk-heading-primary.uk-scrollspy-inview.uk-animation-slide-bottom-small(uk-scrollspy-class="uk-animation-slide-bottom-small")= @country.name
            h2.uk-text-center.uk-text-lead.uk-scrollspy-inview.uk-animation-fade.(uk-scrollspy-class class="uk-visible@s")
              span Sizləri 12 Aprel 2018-ci il saat 12:00-dan 18:00-a kimi keçiriləcək 
              br/
              span Xaricdə təhsil sərgisinə dəvət edirik.
            div.uk-margin-medium.uk-scrollspy-inview.uk-animation-slide-bottom-small.uk-text-center
              button(class="uk-hidden@s uk-button uk-button-secondary ea-button-round uk-icon"  uk-toggle="target: #regform")
                span(uk-icon="icon: bell")
                ' 
                span Qeydiyyatdan Keç
.uk-section.uk-section-default
  .uk-container
    div(class="uk-grid-small uk-child-width-1-2@s uk-child-width-1-4@m uk-flex-center uk-text-center" uk-grid)
      - @country.participants.order(name: :asc).each do |p|
        div
          div(class="uk-card uk-card-default uk-card-body") 
            div.school-logo(style="background-image: url(#{p.logo})")
= render partial: 'shared/registration_form', locals: {source: @country.name}

app/views/layouts/alternative.html.slim
doctype 5
html lang='az'
  head
    title= content_for?(:title) ? content_for(:title) : 'SNG Study Abroad Fair'
    meta[charset='utf-8']
    meta[content='width=device-width, initial-scale=1' name='viewport']
    meta[name='author' content='SABAH']
    meta[name='copyright' content='SNG. Copyright (c) 2018']
    meta[name="description" content="#{content_for?(:description) ? content_for(:description) : 'SNG - Study Abroad.'}"]
    meta[property="og:image" content="#{content_for?(:og_image) ? content_for(:og_image) : image_url('')}"]
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
  body
    .se-pre-con
    .uk-offcanvas-content
      = render 'shared/header'
      = yield
      = javascript_include_tag 'application'

app/views/layouts/application.html.slim
doctype 5
html lang='az'
  head
    title= content_for?(:title) ? content_for(:title) : 'SNG Study Abroad Fair'
    meta[charset='utf-8']
    meta[content='width=device-width, initial-scale=1' name='viewport']
    meta[name='author' content='SNG']
    meta[name='copyright' content='SNG. Copyright (c) 2018']
    meta[name="description" content="#{content_for?(:description) ? content_for(:description) : 'SNG - Study Abroad.'}"]
    meta[property="og:image" content="#{content_for?(:og_image) ? content_for(:og_image) : image_url('')}"]
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
  body
    .se-pre-con
    .uk-offcanvas-content
      = render partial: "shared/notification", flash: flash if !flash.empty?
      = render 'shared/header'
      = yield
      = render 'shared/footer'
      = javascript_include_tag 'application'
      script(src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5abc854a7f5f29ad" type="text/javascript")
      script(src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js")
      javascript:
        $.validate({
          lang: 'en',
          scrollToTopOnError: false
        });

app/views/pages/index.html.slim
- title t('.title')
- description t('.description')
- og_image image_url('cover.jpg')

.uk-section-default.uk-light.uk-position-relative
  div(style="background-image: url(#{image_url('cover.jpg')})" class="uk-background-norepeat uk-background-cover uk-background-center-center uk-section uk-flex uk-flex-middle" uk-height-viewport="offset-top: true")
    .uk-position-cover(style="background-color: rgba(0, 0, 0, 0.4)")
    .uk-width-1-1
      .uk-container
        .uk-margin-remove-adjacent
        .uk-margin-medium
          div
            h2.uk-text-center.h6.uk-scrollspy-inview.uk-animation-fade(class="uk-hidden@s")
              span 12 Aprel 2018-ci il saat 12:00
            h1.uk-text-center.uk-heading-primary.uk-scrollspy-inview.uk-animation-slide-bottom-small(uk-scrollspy-class="uk-animation-slide-bottom-small") Xaricdə Təhsil Sərgisi
            h2.uk-text-center.uk-text-lead.uk-scrollspy-inview.uk-animation-fade.(uk-scrollspy-class class="uk-visible@s")
              span Sizləri 12 Aprel 2018-ci il saat 12:00-dan 18:00-a kimi keçiriləcək 
              br/
              span Xaricdə təhsil sərgisinə dəvət edirik.
            div.uk-margin-medium.uk-scrollspy-inview.uk-animation-slide-bottom-small.uk-text-center
              button(class="uk-hidden@s uk-button uk-button-secondary ea-button-round uk-icon"  uk-toggle="target: #regform")
                span(uk-icon="icon: bell")
                ' 
                span Qeydiyyatdan Keç

.uk-section.uk-section-default
  .uk-container.uk-text-center
    p.uk-text-lead.uk-text-bold Sərgi Hilton Baku Otelində keçiriləcəkdir.
    p.uk-text-lead İştirak etmək üçün qeydiyyat zəruridir.
    div.uk-margin-medium.uk-scrollspy-inview.uk-animation-slide-bottom-small.uk-text-center
      button(class="uk-button uk-button-secondary ea-button-round uk-icon"  uk-toggle="target: #regform")
        span(uk-icon="icon: bell")
        ' 
        span Qeydiyyatdan Keç

.uk-section.uk-section-muted.uk-section-large
  .uk-container
    p Xaricdə təhsil sərgisində Amerika,Böyük Britaniya, Avstraliya, Hollandiya, İspaniya, İtaliya, İsveçrə,Kanada və digər ölkələrdən olan universitetlər iştirak edəcəkdir.Universitetlərin rəsmi şəkildə təmsil olunacağı sərgidə siz universitet nümayəndələri ilə görüşüb universitetlər haqqında daha ətraflı məlumat əldə edə bilərsiniz.

.uk-section.uk-section-default.uk-section-large
  .uk-container
    p Dünyanın reytinqli və nüfuzlu keçmişə sahib olan universitetləri sərgidə iştirak edəcəkdir.Hər il inkişaf edən tədris proqramları ilə dünyanın sayılıb seçilən universitetləri tələbələrinə daha yaxşı təhsili çatdırmaq üçün daim çalışırlar.


.uk-section.uk-section-muted
  .uk-container
    div(uk-slider="center: true")
      .uk-position-relative.uk-visible-toggle
        ul(class="uk-slider-items uk-child-width-1-2@s uk-grid")
          - @countries.each do |c|
            li
              .uk-card.uk-card-default
                .uk-card-media-top
                  = image_tag(c.cover.medium)
                .uk-card-body
                  h3.uk-card-title= c.name
                .uk-card-footer
                  = link_to 'Ətraflı', country_url(c), class: 'uk-button uk-button-text'
        a(class="uk-position-center-left uk-position-small uk-background-default uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous")
        a(class="uk-position-center-right uk-position-small uk-background-default uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next")
      ul(class="uk-slider-nav uk-dotnav uk-flex-center uk-margin")

= render partial: 'shared/registration_form', locals: {source: 'Home Page'}

app/views/pages/success.html.slim
- title t('pages.index.title')
- description t('pages.index.description')
- og_image image_url('cover.jpg')

.uk-section-default.uk-light.uk-position-relative
  div(style="background-image: url(#{image_url('cover.jpg')})" class="uk-background-norepeat uk-background-cover uk-background-center-center uk-section uk-flex uk-flex-middle" uk-height-viewport="offset-top: true")
    .uk-position-cover(style="background-color: rgba(0, 0, 0, 0.4)")
    .uk-width-1-1
      .uk-container
        .uk-margin-remove-adjacent
        .uk-margin-medium
          div
            h1.uk-text-center.uk-heading-primary.uk-scrollspy-inview.uk-animation-slide-bottom-small(uk-scrollspy-class="uk-animation-slide-bottom-small") Qeydiyyatınız tamamlandı!
            h2.uk-text-center.uk-text-lead.uk-scrollspy-inview.uk-animation-fade.(uk-scrollspy-class) Xaricdə Təhsil Sərgisi üçün qeydiyyatdan keçdiyiniz üçün təşəkkür edirik. 
            h2.uk-text-center.uk-text-lead.uk-scrollspy-inview.uk-animation-fade.(uk-scrollspy-class) Sizi tədbirdə görməyi səbirsizliklə gözləyirik.

app/views/shared/_footer.html.slim
.uk-section-secondary.uk-section.uk-section-medium
  footer
    .uk-container
      .uk-grid-large.uk-grid-margin-large.uk-grid.uk-flex.uk-text-center.uk-flex-center(uk-grid)
        div(class="uk-width-2-4@m uk-width-1-2@s")
          h3.uk-h6.uk-text-bold.uk-text-uppercase studynet group
          p.uk-text-muted Studynet Group Aparıcı hazırlıq kursu və təhsil məsləhət mərkəzi 2009-cu ildə yaradılıb və bu günə qədər 7000-dən çox tələbəni dünyanın ən öndə gedən prestijli universitet, kollec və məktəblərinə yerləşdirib.
.uk-section-primary.uk-section.uk-section-xsmall.uk-border-top.uk-text-center
  span.uk-text-small.uk-text-muted &copy; 2018 SNG, All Rights Reserved.

app/views/shared/_header.html.slim
div(class="ea-header-transparent" uk-header)
  div(uk-sticky="animation: uk-animation-slide-top; show-on-up: true; media: 768; cls-active: uk-navbar-sticky; sel-target: .uk-navbar-container")
    .uk-navbar-container.uk-navbar-transparent.uk-light
      .uk-container.uk-container-expand
        nav.uk-navbar(uk-navbar)
          .uk-navbar-left
            = link_to root_path, class: 'uk-navbar-item uk-logo' do
              = image_tag('logo.png', style:"filter: brightness(0) invert(1);")
          .uk-navbar-right
            - if !current_page?('/success')
              button(class="uk-visible@s uk-button uk-button-default ea-button-round uk-icon" uk-toggle="target: #regform")
                span(uk-icon="icon: bell")
                ' 
                span Qeydiyyat
            - if current_page?('/success')
              = link_to 'ANA SƏHİFƏ', root_path, class: 'uk-button uk-button-default ea-button-round'

              
            

app/views/shared/_list_modal.html.slim
<div id="listmodal" uk-modal>
    <div class="uk-modal-dialog">

        <button class="uk-modal-close-default" type="button" uk-close></button>

        <div class="uk-modal-header">
            <h2 class="uk-modal-title">Headline</h2>
        </div>

        <div class="uk-modal-body" uk-overflow-auto>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

        </div>

        <div class="uk-modal-footer uk-text-right">
            <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
            <button class="uk-button uk-button-primary" type="button">Save</button>
        </div>

    </div>
</div>

app/views/shared/_notification.html.slim
- if notice.present? || alert.present?
  .uk-margin-remove-bottom(uk-alert)
    .uk-container
      button.uk-alert-close(type="button" uk-close )
      p
        span= notice
        span= alert

app/views/shared/_registration_form.html.slim
#regform(uk-modal class="uk-flex-top")
  .uk-modal-dialog.uk-margin-auto-vertical
    button(class="uk-modal-close-default" type="button" uk-close)
    .uk-modal-header
      h2.uk-modal-title.uk-text-center QEYDİYYAT FORMU
    .uk-modal-body
      .inner-form
        = form_tag attend_url, class: 'uk-form-stacked' do
          = hidden_field_tag 'fair_confirmation[source]', source
          .uk-margin
            = label_tag 'first_name', "Ad", class: 'uk-form-label'
            .uk-form-controls
            = text_field_tag 'fair_confirmation[first_name]', nil, class: 'uk-input', placeholder: "", data: { validation: "length", "validation-length": "3-20" }

          .uk-margin
            = label_tag 'last_name', "Soyad", class: 'uk-form-label'
            .uk-form-controls
              = text_field_tag 'fair_confirmation[last_name]', nil, class: 'uk-input', placeholder: "", data: { validation: "length", "validation-length": "3-20" }

          .uk-margin
            = label_tag 'phone', "Telefon", class: 'uk-form-label'
            .uk-form-controls
              = phone_field_tag 'fair_confirmation[phone]', nil, class: 'uk-input', placeholder: "", data: { validation: "required" }

          .uk-margin
            = label_tag 'email', "E-poçt", class: 'uk-form-label'
            .uk-form-controls
              = text_field_tag 'fair_confirmation[email]', nil, class: 'uk-input', placeholder: "", data: { validation: "email" }
          
          .uk-margin
            .uk-form-controls
              = submit_tag "Göndər", class: 'uk-button uk-button-default ea-button-round', data: { disable_with: "Please wait..." }
        